title: Exercícios em Python
description: Trilha de aprendizado com exercícios organizados por tópicos e dificuldade.
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

# Isso aponta pro seu CSS customizado
include:
  - assets/css/style.scss
